#!/usr/bin/env bash
# Fluidd installation script
# Installs Fluidd and nginx
# Written by Raymond Himle
# Thanks to meteyou
# Revamped by KwadFan
# GPL V3
########


# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

### Install fluidd.cfg
unpack /filesystem/home/pi /home/pi pi

echo_green "Installing Fluidd Webfrontend ..."

### install all deps at once for time consumption reasons.
## APT: Update Repo Database and install Dependencies

apt update && apt install ${FLUIDD_DEPS} -y

### Preparing nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/fluidd /etc/nginx/sites-enabled/

### Download and Install Fluidd Web Frontend
pushd /home/${BASE_USER}
sudo -u ${BASE_USER} wget -q --show-progress -O fluidd.zip "${FLUIDD_URL}"
sudo -u ${BASE_USER} unzip fluidd.zip -d /home/pi/fluidd
## cleanup
rm /home/pi/fluidd.zip
popd

### Link logfiles to klipper_logs
ln -s /var/log/nginx/fluidd-access.log /home/pi/klipper_logs/
ln -s /var/log/nginx/fluidd-error.log /home/pi/klipper_logs/

# Unpack root at the end, so files are modified before
unpack /filesystem/root /